### ISSUE TITLE
Question obout using Swin-T as backbone

### ISSUE THREAD

**Issue by DUT-CSJ** [CODE4UVOS/HFAN#2]
Hello, in your ablation study, Swin-T is used to be backbone. 
However, the official implementation of Swin-Transformer only provide resolution of 224*224. 
I wanna know how you deal with the difference of resolution, using random initialization or some method to transfer resolution?
Hope for your reply.

**Comment by CODE4UVOS** [comment]
Currently, the primary task of computer vision is classification, followed by the downstream tasks it drives (detection, segmentation).

Most current backbones (either CNN or Transformer) are trained with ImageNet at 224x224 resolution. Only the FC layer needs to be removed for downstream tasks and then fine-tuned.

Regarding these theories, I suggest you refer to [PVT](https://github.com/whai362/PVT) because the MiT backbone is very similar to PVT-v2.

And you can also use PVT-v2 to reproduce our method. That would be a nice learning journey.
